setInterval
Tatumura/ChatSpace pull request #11
Opened 2019-03-24 12:47 UTC by Tatumura

#what
自動更新の実装
#why
5秒ごとに更新をかけることでメッセージをすぐに確認することができる。

2019-03-24 12:51 UTC, Tatumura commented
https://gyazo.com/94326d5e0b064b8a11ca2ed1089eb77a

2019-03-24 12:54 UTC, yuki-uchida requested changes

2019-03-24 12:54 UTC, yuki-uchida commented on app/assets/javascripts/message.js
>    function buildHTML(message) {
なんのHTMLをbuildするのかもわかる名前だと良いですね

2019-03-24 12:54 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +      .done(function(data) {
dataよりも具体的な名前でお願いします

2019-03-24 22:34 UTC, Tatumura commented
修正しました。

2019-03-24 22:39 UTC, Tatumura commented
修正しました。

2019-03-25 02:10 UTC, miyagit commented on app/assets/javascripts/message.js
>        $('.textbox').val('')
こちらform属性のresetメソッドを使いましょう。

2019-03-25 02:46 UTC, Tatumura commented
修正しました。

2019-03-25 02:53 UTC, miyagit commented on app/assets/javascripts/message.js
> +      $('.textbox').reset();
これってformタグのクラスですか？

ぱっと見わかりにくいので、idで指摘するかわかりやすいクラス名にしましょう。

2019-03-26 03:22 UTC, Tatumura commented
修正しました。

2019-03-26 03:28 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +      $('form')[0].reset();
こちらがあるので44行目は不要になりますかね

2019-03-28 00:50 UTC, Tatumura commented
修正しました。

2019-03-28 02:05 UTC, miyagit reviewed
logディレクトリは.gitignoreに入れましょう。

2019-03-28 02:05 UTC, miyagit commented on app/assets/javascripts/message.js
> +            .fail(function(json) {
インデント修正しましょう。

2019-03-28 02:21 UTC, Tatumura commented
修正しました。

2019-03-28 02:28 UTC, TOMARUMARU approved these changes
LGTM

2019-03-30 14:04 UTC, merged